sudo: false
language: node_js
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
node_js: 
  - 5.10
  - 4.4
notifications:
  slack: devops-training-spb:EKrhbizOMW4MGPBtII3eRJCy
