sudo: false
language: node_js
node_js: 
  - 5.10
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:EKrhbizOMW4MGPBtII3eRJCy
deploy:
  provider: heroku
  api_key:
    secure: RZxuDgXNoMkLylrJTMkjbnAeDgQfLRHDiZHX5Cw/k3lJSD9JY+J1jX7QN+Rs5oCRoUpegPWRV5VZkihwp7sQ/HePYNkjsobCaaob+FILm+wOINWz1XjfPZGmkqNWNsDcrkcrWDUY58cFgXLYNqwjbGJZI7fTEK+LdwAkM+WqtDN1l5msEIzrpIGdwvbVL2MrLdWt7n2hAidiy6qHspfvSkKKzUW8aaLwk0Divzv/t41Of6F4VS498BsHY7iS3/ZkwXCut+8u6KqfaBuSdyuZmcHC30PQMZNS/5/BVw3ZsyTMlijfEI6pFS7XDDDDR7ZcZh5NHhF5PLkch5JyLiGfm8NwRSO3fajHbcuMT7b8m4cW2rK3t7xlTBKHSv3W7NqbxjSL8ihqFFfXvm1vomwmX3se16FKGd5EkEd9ennuFnY4i9Yz3QOipJoaHkrx6AV2g3f25FquwuN/NO/5Tgi9GRsEtMjgK5KY9qK1NQBNK7q+vhnosisrsnww7scx2DQHBq1A1G353R3v6druHWUMB/MBGwhqp8Vlis/JUXt8zMx+xTA2wCQxGwun/l+OMuXGqTrhETvG8JXpi79xdpKU0hViatt8LAb4ZYuDk0ocjdkAGo/z0Ylv7Ri+kANthLpUQBEurecMsdJZ9nFgCa3GZO/Dlaaqa5xtUnKssI+TRQ0=
